version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: db
    expose:
      - 5432
    env_file:
      - .env

  app:
    build: .
    restart: unless-stopped
    container_name: sheethappens
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
